const UserModel = require('../UserModel/usermodel')
const otp_generator = require('otp-generator')
const bcrypt = require('bcrypt')
const crypto = require('crypto')
const sendEmail = require('../Email service/Email')
const jwt = require('jsonwebtoken')

// Generate password yang dijamin lolos passwordRegex frontend:
// /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/
// otp-generator memakai special '#!&@' (ada '#' yang ditolak frontend) dan
// tidak menjamin tiap kategori muncul, jadi tidak dipakai untuk password Google.
const GOOGLE_PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/
const generateGooglePassword = (length = 12) => {
    const lower = 'abcdefghjkmnpqrstuvwxyz'
    const upper = 'ABCDEFGHJKMNPQRSTUVWXYZ'
    const digits = '23456789'
    const specials = '@$!%*?&'
    const all = lower + upper + digits + specials
    for (let attempt = 0; attempt < 5; attempt++) {
        const chars = [
            lower[crypto.randomInt(0, lower.length)],
            upper[crypto.randomInt(0, upper.length)],
            digits[crypto.randomInt(0, digits.length)],
            specials[crypto.randomInt(0, specials.length)],
        ]
        while (chars.length < length) {
            chars.push(all[crypto.randomInt(0, all.length)])
        }
        // shuffle Fisher-Yates agar posisi kategori wajib acak
        for (let i = chars.length - 1; i > 0; i--) {
            const j = crypto.randomInt(0, i + 1)
            ;[chars[i], chars[j]] = [chars[j], chars[i]]
        }
        const password = chars.join('')
        if (GOOGLE_PASSWORD_REGEX.test(password)) return password
    }
    throw new Error('Failed to generate compliant password')
}


const register = async (req,res)=>{
    try {

        console.log(req.body);

        const isUserExisting = await UserModel.findOne({email:req.body.email})

        if(isUserExisting) {
            console.log("User already exists");
            
            return res.status(400).json({message:`User with ${req.body.email} already existing.`})
        }

        const verificationToken = otp_generator.generate(6,{upperCaseAlphabets: false, specialChars: false})

        const expires = new Date();
        expires.setMinutes(expires.getMinutes() + 5);

        const hashedPassword = await bcrypt.hash(req.body.password,10)

        const newUser = await UserModel({
            email: req.body.email,
            username: req.body.username,
            password: hashedPassword,
            verificationToken: {
                token: verificationToken,
                expires: expires

            }
        })

        console.log(newUser);
        await newUser.save()

        const emailbody = `<p>Please click on the link verify your account <b>http://localhost:5000/user/verify/${verificationToken}</b>VERIFY ACCOUNT</p>`
        const subject = `Verification Email`

        await sendEmail(req.body.email,subject,emailbody)
        



        res.json({message:"Verification link sent to your EMAIL."})
    } catch (error) {
        res.json({message: "Something went wrong"})
    }
}

const login = async (req,res)=>{
    try {
        console.log(req.body);

        const isUserExisting = await UserModel.findOne({email:req.body.email})
        console.log(isUserExisting);
        
        if(!isUserExisting) {

            if(req.body.autoGenerated){

            const password = otp_generator.generate(12,{upperCaseAlphabets: true, specialChars: true})

            const hashedpassword = await bcrypt.hash(password,10)
            
            const newUser = await UserModel({
            email: req.body.email,
            username: req.body.username,
            password: hashedpassword,
            isVerified: true
        })

            console.log(newUser);
            await newUser.save()
            
            const jwtPayload = {
            id : newUser.id
        }

        const token = jwt.sign(jwtPayload,process.env.SECRET,{expiresIn:'10m'})

                const emailbody = `<p>Account created successfully. Your password is${password}. please Change it</p>`
                const subject = `Account creat VIA Social`

            await sendEmail(req.body.email,subject,emailbody)

            return res.status(200).json({message: "Logged in VIA social", token})

            }


            return res.status(400).json({message:`User with ${req.body.email} don't existing.`})
        }

        if(!isUserExisting.isVerified){
            return res.status(400).json({message:`User is not Verified. Please click the link in your Email to verify`})

        }

        const isPasswordCorrect = await bcrypt.compare(req.body.password,isUserExisting.password)

        if(!isPasswordCorrect){
            return res.status(400).json({message:`Invalid Credentials.`})
        }

        // create JWT
        
        const jwtPayload = {
            id : isUserExisting.id
        }

        const token = jwt.sign(jwtPayload,process.env.SECRET,{expiresIn:'10m'})
        console.log(token);
        
        
        res.json({message:`User Logged in succesfuly`,token})
    } catch (error) {
        res.json.status(500)({message:`Something went wrong`})
    }
}

const VerifyUser = async (req,res) => {
    try {
        console.log(req.params);
        
        const token = req.params.token
        
        const isTokenValid = await UserModel.findOne(
            {
                'verificationToken.token':token,
                'verificationToken.expires': {$gt : new Date()}
            })
            console.log(isTokenValid);

            if(!isTokenValid) {
                return res.send(`<p>Token invalid or expired</p> <a href="http://localhost:5000/user/resendverification/${token}">Resend verification</a>`)
            }

            if(isTokenValid.isVerified){
                return res.send("Account already Verified successfuly.Please Login")
            }

            isTokenValid.isVerified = true

            await isTokenValid.save()


            res.send("Account Verified successfuly")
    } catch (error) {
        console.log(error);
        res.status(500).json({message:"Server Error"})
        
    }
}

    const resendverification = async (req,res) => {
        try {
            
            const token = req.params.token

            const user = await UserModel.findOne(
            {
                'verificationToken.token':token,
                'isVerified': false
            })

            if(!user) {
                return res.status(400).send("Invalid token or account already verified")
            }

            const verificationToken = otp_generator.generate(6,{upperCaseAlphabets: false, specialChars: false})

            const expires = new Date();
            expires.setMinutes(expires.getMinutes() + 5);

            user.verificationToken = {
                expires: expires,
                token: verificationToken
            }

            await user.save()
            

            const emailbody = `<p>Please click on the link verify your account <b>http://localhost:5000/user/verify/${verificationToken}</b>VERIFY ACCOUNT</p>`
            const subject = `Verification Email`

            await sendEmail(user.email,subject,emailbody)
            res.send("Please cek Your email for a new verification")


        } catch (error) {
            console.log("RESEND ERROR:", error);
            res.status(500).send("Something wrong");
            
        }
        
    }

    const updateUser = async(req,res)=>{
        try {
            console.log(req.decodeData);
            res.json({message: req.decodeData})
        } catch (error) {
            res.json({message:`Something went wrong`})
        }
    }

    const googleLogin = async (req,res)=>{
        try {
            console.log("GOOGLE LOGIN:", req.body);

            const { email, username } = req.body;

            if(!email) {
                return res.status(400).json({message:`Email from Google is required.`})
            }

            let user = await UserModel.findOne({email})
            console.log(user);

            // Auto-register khusus Google: email sudah diverifikasi Google,
            let isNewUser = false
            let plainPasswordForEmail = null
            if(!user) {
                plainPasswordForEmail = generateGooglePassword(12)

                const hashedPassword = await bcrypt.hash(plainPasswordForEmail,10)

                user = await UserModel({
                    email,
                    username: username || email.split("@")[0],
                    password: hashedPassword,
                    isVerified: true
                })

                await user.save()
                isNewUser = true
                console.log("GOOGLE LOGIN: new user created", user.email);

                // Kirim plain password (SEBELUM hash) agar bisa dipakai login manual.
                try {
                    const subject = `Account created VIA Google`
                    const emailbody = `<p>Account created successfully via Google login.</p><p>Your password for manual login is: <b>${plainPasswordForEmail}</b></p><p>Please keep it safe and change it soon.</p>`
                    await sendEmail(email,subject,emailbody)
                    console.log("GOOGLE LOGIN: password email sent to", email);
                } catch (mailError) {
                    console.log("GOOGLE LOGIN: failed to send password email, login continues:", mailError?.message || mailError);
                }
            }

            // Khusus path Google: email terbukti milik user, auto-verify jika belum.
            // Flow login manual tetap menolak belum-verified (tidak diubah).
            if(!user.isVerified){
                user.isVerified = true
                await user.save()
            }

            // create JWT (tanpa cek password, karena identitas sudah diverifikasi Google)
            const jwtPayload = {
                id : user.id
            }

            const token = jwt.sign(jwtPayload,process.env.SECRET,{expiresIn:'10m'})
            console.log(token);

            res.json({message: isNewUser ? `Google account created & logged in successful` : `Google login successful`,token})
        } catch (error) {
            console.log("GOOGLE LOGIN ERROR:", error);
            res.status(500).json({message:`Something went wrong`})
        }
    }

module.exports = {register,login,VerifyUser,resendverification,updateUser,googleLogin}

